/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FalseReturnERC20Mock } from "./FalseReturnERC20Mock";
export type { NoReturnERC20Mock } from "./NoReturnERC20Mock";
