/** Browser-safe operator display constants. */
export const DISPLAY = {
  SHORT_HASH_BYTES: 4,
  SHORT_HASH_HEX_CHARS: 8,
  ENDPOINT_PREFIX_CHARS: 8,
  ENDPOINT_SUFFIX_CHARS: 4,
  HEALTH_FLOW_EDGE_LIMIT: 12,
} as const;

/** Browser-safe QA and release-evidence contract. */
export const QA = {
  RUN_WINDOW_STEP: 80,
  SHARD_WINDOW_STEP: 80,
  HISTORY_WINDOW_STEP: 80,
  LEDGER_WINDOW_STEP: 80,
  ARTIFACT_WINDOW_STEP: 40,
  RECENT_TREND_LIMIT: 12,
  HISTORY_PREVIEW_LIMIT: 12,
  BROWSER_ISSUE_PREVIEW_LIMIT: 8,
  STORY_TAG_LIMIT: 12,
  SHARD_TIMELINE_STEP_LIMIT: 80,
  SHARD_SLOW_STEP_LIMIT: 12,
  LOG_TAIL_LINES: 80,
  BOOTSTRAP_PAIR_PREVIEW_LIMIT: 6,
  BOOTSTRAP_CROSS_ROUTE_PREVIEW_LIMIT: 8,
  HISTORY_DEFAULT_LIMIT: 120,
  HISTORY_MAX_LIMIT: 500,
  HISTORY_BACKFILL_DEFAULT_LIMIT: 500,
  HISTORY_BACKFILL_MAX_LIMIT: 2_000,
  RETENTION_MIN_DAYS: 30,
  RESTART_CONFIRM: 'RUN',
  RESTART_ABORT_CONFIRM: 'ABORT_RESTART',
  HISTORY_BACKFILL_CONFIRM: 'BACKFILL_QA_HISTORY',
  RETENTION_CONFIRM: 'DELETE_OLDER_THAN_30_DAYS',
  PHASE_BUDGET_MS: {
    preflight: 1_000,
    anvilBoot: 5_000,
    apiBoot: 5_000,
    apiHealthy: 5_000,
    viteBoot: 5_000,
    playwright: 5_000,
  },
} as const;
