#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

rm -rf data*
rm -rf isolate*

rsync . root@failsafe.network:~/fs -rv  --exclude '.git' --exclude 'node_modules' --exclude 'dist' --exclude '.cache'

ssh root@failsafe.network <<'ENDSSH'
cd ~/fs
./prod
ENDSSH
