#!/bin/bash

# Rotate logs for clarity
if [ -f /etc/logrotate.d/pm2-root ]; then
  logrotate -f /etc/logrotate.d/pm2-root
fi

pm2 delete all

killall Failsafe 2>/dev/null

rm -rf isolate*
rm -rf data*

./install
npm run build

db=mysql:root:123123
#db=postgres:postgres:123123
maxport=8008

#--node-args="--prof"

node fs --genesis=test --db=$db
pm2 start fs.js --no-autorestart --name fs -- -p443 --silent --wallet-dist --db=$db --monkey=$maxport

for i in $(seq 8001 $maxport); do
  rsync -q -rva --exclude=offchain data/* data$i
  cmd="pm2 start fs.js --no-autorestart --name fs$i -- -p$i --username=$i --pw=password --silent --datadir=data$i --wallet-dist --db=$db"
  if (( i < 8004 )); then
    ${cmd} --monkey=$maxport
  else
    ${cmd} --monkey=$maxport
  fi
done

#node --prof fs.js -p443 --silent --wallet-dist --db=$db

