#!/bin/bash
set -o nounset
set -o errexit
set -o pipefail

rm -rf data*
rm -rf isolate*

killall Failsafe 2>/dev/null || true

function pm2() {
  node_modules/.bin/pm2 "$@"
}
# TODO move genesis to simulate.config
if node fs --genesis=test --db=mysql:root:123123 | grep "Genesis done"; then
  maxport=8015
  echo "Generating with maxport $maxport"

  for i in $(seq 8001 $maxport); do
    rsync -q -rva --exclude=offchain data/* data$i
  done

  pm2 flush
  pm2 delete all || true
  pm2 start simulate.config.js
  pm2 attach $(node -p "`pm2 id fs`[0]")

fi
