import type { SurfaceId } from './surfaces';

export type CapabilityStatus = 'unstarted' | 'in_progress' | 'implemented' | 'verified' | 'blocked';

export type CapabilityDefinition = Readonly<{
  id: string;
  owner: SurfaceId;
  routes: readonly `/${string}`[];
  currentSources: readonly string[];
  behavior: readonly string[];
  status: CapabilityStatus;
}>;

export const CAPABILITIES = [
  {
    id: 'site-public-information',
    owner: 'site',
    routes: ['/', '/install', '/rcpan', '/releases', '/reviews', '/unicast', '/market-cap'],
    currentSources: [
      'frontend/src/routes/+page.svelte',
      'frontend/src/routes/install/+page.svelte',
      'frontend/apps/site/src/landing-page.tsx',
      'frontend/apps/site/src/install-page.tsx',
      'frontend/apps/site/src/rcpan-page.tsx',
      'frontend/apps/site/src/unicast-page.tsx',
      'frontend/apps/site/src/releases-page.tsx',
      'frontend/apps/site/src/reviews-page.tsx',
      'frontend/apps/site/src/market-cap-page.tsx',
      'frontend/packages/ui/src/market-cap-page-model.ts',
      'frontend/packages/ui/src/release-catalog.ts',
      'frontend/packages/ui/src/release-chart.ts',
      'frontend/packages/ui/src/release-signature.ts',
      'frontend/packages/ui/src/reviews-model.ts',
      'frontend/packages/ui/src/rcpan/microscope-model.ts',
      'frontend/packages/ui/src/rcpan/microscope-playground.ts',
      'frontend/packages/ui/src/rcpan/microscope-timeline.ts',
    ],
    behavior: ['public navigation', 'install detection', 'deterministic RCPAN dispute microscope', 'broadcast/unicast scale visualization', 'verified release ledger', 'AI review prompt slideshow', 'live market-cap data'],
    status: 'implemented',
  },
  {
    id: 'docs-reader',
    owner: 'docs',
    routes: ['/docs'],
    currentSources: [
      'frontend/src/routes/docs/+page.svelte',
      'frontend/packages/ui/src/docs-page-model.ts',
      'frontend/packages/ui/src/safe-markdown.ts',
      'frontend/packages/runtime-client/src/boundary.ts',
      'frontend/apps/docs/src/docs-app.tsx',
      'frontend/docs-catalog.js',
    ],
    behavior: ['catalog navigation and search', 'live/archive scope', 'safe Markdown rendering', 'deep links, anchors, and history', 'deterministic docs and llms outputs'],
    status: 'implemented',
  },
  {
    id: 'wallet-shell-and-identity',
    owner: 'wallet',
    routes: ['/app', '/address', '/testnet'],
    currentSources: [
      'frontend/packages/browser/src/wallet-boot-lifecycle.ts',
      'frontend/packages/browser/src/wallet-brainvault-finalization.ts',
      'frontend/packages/browser/src/wallet-brainvault-worker-resilience.ts',
      'frontend/packages/browser/src/wallet-brainvault-worker-scheduling.ts',
      'frontend/packages/browser/src/wallet-brainvault-worker-validation.ts',
      'frontend/packages/browser/src/wallet-deploy-version.ts',
      'frontend/packages/browser/src/wallet-identity-entry.ts',
      'frontend/packages/browser/src/wallet-node-brainvault-validation.ts',
      'frontend/packages/browser/src/wallet-node-mnemonic-reveal.ts',
      'frontend/packages/browser/src/wallet-recovery-choice.ts',
      'frontend/packages/browser/src/wallet-recovery-discovery.ts',
      'frontend/packages/browser/src/wallet-recovery-rehearsal.ts',
      'frontend/packages/browser/src/wallet-runtime-bootstrap.ts',
      'frontend/packages/browser/src/wallet-runtime-consent.ts',
      'frontend/packages/browser/src/wallet-runtime-opening.ts',
      'frontend/packages/browser/src/wallet-runtime-preferences.ts',
      'frontend/packages/browser/src/wallet-shell-state.ts',
      'frontend/packages/ui/src/demo-accounts.ts',
      'frontend/packages/ui/src/runtime-creation-model.ts',
      'frontend/src/lib/components/Views/RuntimeCreation.svelte',
      'frontend/src/routes/app/+layout.svelte',
      'frontend/src/routes/app/+page.svelte',
      'frontend/src/routes/address/+page.svelte',
      'frontend/src/routes/testnet/+page.svelte',
      'frontend/apps/wallet/src/testnet-page.tsx',
      'frontend/config/wallet-flow-audit.ts',
    ],
    behavior: [
      'boot and shell',
      'deterministic browser BrainVault finalization decisions',
      'deterministic browser BrainVault worker sizing and resilience decisions',
      'deterministic browser BrainVault retry, dispatch, and worker-scaling decisions',
      'validated browser BrainVault worker messages and shard completions',
      'generation-safe local and remote boot sequencing',
      'validated deploy-version persistence, reset, and recovery decisions',
      'canonical identity-mode selection, sensitive-field clearing, and keyboard navigation',
      'deterministic node BrainVault access, progress, result, and timing validation',
      'generation-safe node mnemonic reveal coordination',
      'deterministic recovery candidate selection, merge ordering, and continuation',
      'generation-safe recovery discovery coordination',
      'verified mnemonic recovery-rehearsal transitions and reset policy',
      'ordered local-pairing, remote-import, and consent bootstrap',
      'validated remote consent and embedded cancellation ordering',
      'deterministic local unlock and Runtime creation planning',
      'deterministic Runtime preference decoding and serialization',
      'framework-neutral wallet shell phase precedence',
      'identity selection',
      'onboarding and settings',
      'testnet launcher and disposable identities',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-browser-lifecycle',
    owner: 'wallet',
    routes: ['/app', '/testnet'],
    currentSources: [
      'frontend/packages/browser/src/active-tab-lock.ts',
      'frontend/packages/browser/src/wallet-runtime-suspension.ts',
      'frontend/packages/browser/src/browser-runtime-reset.ts',
      'frontend/packages/browser/src/hard-reset-request.ts',
      'frontend/src/lib/utils/control/resetEverything.ts',
    ],
    behavior: [
      'validated destructive reset',
      'cross-tab reset notification',
      'exclusive cross-tab Runtime ownership and quiesced takeover',
      'storage, cache, and service-worker cleanup',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-runtime-discovery',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/packages/browser/src/runtime-adapter-session.ts',
      'frontend/packages/browser/src/runtime-module-loader.ts',
      'frontend/packages/browser/src/wallet-embedded-runtime-session.ts',
      'frontend/packages/runtime-client/src/runtime-adapter-activation.ts',
      'frontend/packages/runtime-client/src/runtime-handle.ts',
      'frontend/packages/runtime-client/src/remote-runtime-request.ts',
      'frontend/packages/runtime-client/src/runtime-query-client.ts',
      'frontend/packages/runtime-client/src/runtime-query-observer.ts',
      'frontend/packages/runtime-client/src/runtime-selection.ts',
      'frontend/packages/runtime-client/src/runtime-view-catchup.ts',
      'frontend/packages/runtime-client/src/runtime-view-loader.ts',
      'frontend/packages/runtime-client/src/runtime-view-model.ts',
      'frontend/packages/runtime-client/src/runtime-view-projections.ts',
      'frontend/packages/runtime-client/src/runtime-view-publication.ts',
      'frontend/packages/runtime-client/src/runtime-view-refresh.ts',
      'frontend/packages/runtime-client/src/runtime-view-selection.ts',
      'frontend/packages/runtime-client/src/runtime-view-state.ts',
      'frontend/packages/runtime-client/src/ws-url.ts',
      'frontend/packages/runtime-client/src/runtime-failure.ts',
      'frontend/apps/wallet/src/app-shell.tsx',
      'frontend/apps/wallet/src/app-shell-model.ts',
      'frontend/apps/wallet/src/wallet-embedded-runtime-adapter.ts',
      'frontend/apps/wallet/src/wallet-embedded-runtime-bootstrap.ts',
      'frontend/apps/wallet/src/wallet-embedded-runtime.ts',
      'frontend/apps/wallet/src/identity-onboarding.tsx',
      'frontend/apps/wallet/src/identity-onboarding-model.ts',
      'frontend/apps/wallet/src/identity-recovery.tsx',
      'frontend/apps/wallet/src/wallet-settings.tsx',
      'frontend/apps/wallet/src/wallet-settings-model.ts',
      'frontend/apps/wallet/src/wallet-diagnostics.tsx',
      'frontend/apps/wallet/src/wallet-diagnostics-model.ts',
      'frontend/apps/wallet/src/wallet-financial-health-source.ts',
      'frontend/apps/wallet/src/wallet-runtime-read-boundary.ts',
      'frontend/src/lib/utils/runtime/runtimeConnection.ts',
    ],
    behavior: [
      'Runtime discovery',
      'validated hash bootstrap and query rejection',
      'tab-confined Runtime authority and rollback-safe adapter selection',
      'framework-neutral Runtime handle identity, permissions, and readiness',
      'framework-neutral adapter activation ordering and rollback',
      'framework-neutral cached Runtime projection reads and path validation',
      'framework-neutral latest-read Runtime query subscriptions and snapshots',
      'one-writer latest-intent Runtime selection',
      'framework-neutral committed-height RuntimeView catch-up',
      'framework-neutral injected RuntimeView loading and outcomes',
      'framework-neutral RuntimeView query, pagination, and height model',
      'framework-neutral selection-scoped detached RuntimeView projection reads',
      'framework-neutral latest-wins RuntimeView publication coordination',
      'framework-neutral RuntimeView refresh leases and invalidation',
      'framework-neutral RuntimeView selection snapshots and revisions',
      'framework-neutral RuntimeView snapshot and height transitions',
      'explicit remote attachment consent',
      'reconnect and failure states',
      'React-owned Runtime and authority overview shell',
      'React-owned Brain Vault and mnemonic identity entry with secret-free review',
      'React-owned mnemonic recovery rehearsal with public-address-only matching',
      'React-owned browser preferences for auth appearance and BrainVault worker caps',
      'React-owned redacted Runtime, browser-capability, and deploy-version diagnostics',
      'React-owned height-pinned financial-health reads with bounded retry and teardown',
      'React wallet WP6 requirement audit with explicit cross-work-package deferrals',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-recovery',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: ['frontend/src/lib/utils/recovery'],
    behavior: ['tower onboarding', 'recovery', 'push wake'],
    status: 'unstarted',
  },
  {
    id: 'wallet-finance',
    owner: 'wallet',
    routes: ['/app', '/address'],
    currentSources: [
      'frontend/src/lib/components/Entity',
      'frontend/apps/wallet/src/wallet-portfolio.tsx',
      'frontend/apps/wallet/src/wallet-portfolio-model.ts',
      'frontend/apps/wallet/src/wallet-portfolio-source.ts',
      'frontend/apps/wallet/src/wallet-financial-health.tsx',
      'frontend/apps/wallet/src/wallet-financial-health-model.ts',
      'frontend/apps/wallet/src/wallet-financial-health-solvency.ts',
    ],
    behavior: [
      'assets and accounts',
      'credit and collateral',
      'debt, solvency, and disputes',
      'React-owned committed RuntimeView assets and Account capacity projection',
      'React-owned debt, Runtime solvency evidence, Account dispute gates, and committed history',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-payments-and-markets',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/src/lib/components/Entity/swap',
      'frontend/packages/runtime-client/src/payment-command.ts',
      'frontend/packages/runtime-client/src/payment-command-types.ts',
      'frontend/packages/runtime-client/src/xln-invoice.ts',
      'frontend/packages/browser/src/runtime-command-intent.ts',
      'frontend/packages/browser/src/runtime-command-intent-codec.ts',
      'frontend/packages/browser/src/runtime-command-journal-indexed-db.ts',
      'frontend/packages/browser/src/runtime-command-journal-keyring.ts',
      'frontend/packages/browser/src/runtime-command-journal-storage.ts',
      'frontend/apps/wallet/src/wallet-payments.tsx',
      'frontend/apps/wallet/src/wallet-payment-source.ts',
      'frontend/apps/wallet/src/wallet-payment-operations-model.ts',
      'frontend/apps/wallet/src/wallet-markets.tsx',
      'frontend/apps/wallet/src/wallet-market-source.ts',
      'frontend/apps/wallet/src/wallet-market-model.ts',
      'frontend/apps/wallet/src/wallet-market-command.ts',
    ],
    behavior: [
      'pay and receive',
      'invoices and moves',
      'orders, routing, and settlement',
      'React-owned Runtime route quotes and idempotent payment command retry',
      'React-owned canonical invoices and bounded reserve, collateral, settlement, and lending operations',
      'React-owned Runtime orderbooks, canonical same-j order and cancel commands, cross-j lifecycle, and persisted activity',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-native-and-offline',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/src/lib/native',
      'frontend/capacitor.config.ts',
      'frontend/config/generated-inputs.ts',
      'frontend/apps/wallet/index.html',
      'frontend/static/site.webmanifest',
      'frontend/static/push-wake-sw.js',
      'frontend/static/route-mode.js',
    ],
    behavior: [
      'deep links',
      'PWA and offline lifecycle',
      'mobile, desktop, and extension packaging',
      'deterministic PWA and push-wake assets',
    ],
    status: 'in_progress',
  },
  {
    id: 'ops-health-and-qa',
    owner: 'ops',
    routes: ['/health', '/qa', '/qa/hlt'],
    currentSources: [
      'frontend/packages/runtime-client/src/admin-health.ts',
      'frontend/packages/runtime-client/src/rpc-health.ts',
      'frontend/packages/runtime-client/src/qa-admin-evidence.ts',
      'frontend/packages/runtime-client/src/qa-boundary.ts',
      'frontend/packages/runtime-client/src/qa-cockpit-helpers.ts',
      'frontend/packages/runtime-client/src/qa-hlt.ts',
      'frontend/packages/runtime-client/src/qa-performance-trend.ts',
      'frontend/packages/runtime-client/src/qa-scenario-player.ts',
      'frontend/packages/runtime-client/src/qa-test-ledger.ts',
      'frontend/packages/runtime-client/src/qa-types.ts',
      'frontend/packages/browser/src/qa-api-client.ts',
      'frontend/src/routes/health/+page.svelte',
      'frontend/src/routes/qa/+page.svelte',
      'frontend/src/routes/qa/hlt/+page.svelte',
      'frontend/apps/ops/src/ops-health-model.ts',
      'frontend/apps/ops/src/ops-health-source.ts',
      'frontend/apps/ops/src/ops-health-runtime.ts',
      'frontend/apps/ops/src/ops-health.tsx',
      'frontend/apps/ops/src/ops-hlt-model.ts',
      'frontend/apps/ops/src/ops-hlt-source.ts',
      'frontend/apps/ops/src/ops-hlt-runtime.ts',
      'frontend/apps/ops/src/ops-hlt-controls.tsx',
      'frontend/apps/ops/src/ops-hlt-progress.tsx',
      'frontend/apps/ops/src/ops-hlt.tsx',
      'frontend/apps/ops/src/ops-qa-model.ts',
      'frontend/apps/ops/src/ops-qa-source.ts',
      'frontend/apps/ops/src/ops-qa-actions.ts',
      'frontend/apps/ops/src/ops-qa-runtime.ts',
      'frontend/apps/ops/src/ops-qa.tsx',
    ],
    behavior: [
      'health state',
      'QA evidence',
      'HLT controls and results',
      'React-owned live health and RPC readiness with bounded retry, refresh, stale evidence, and teardown',
      'React-owned canonical HLT preview, record/replay/abort controls, active-run polling, and authoritative progress evidence',
      'React-owned QA run ledger, verdict, protected artifacts, restart authority, history maintenance, and page teardown',
    ],
    status: 'implemented',
  },
  {
    id: 'ops-runs-scenarios-and-ai',
    owner: 'ops',
    routes: ['/runs', '/scenarios', '/ai'],
    currentSources: [
      'frontend/src/routes/runs/+page.svelte',
      'frontend/src/routes/scenarios/+page.svelte',
      'frontend/src/routes/ai/[[chatId]]/+page.svelte',
      'frontend/packages/browser/src/runtime-scenario-source.ts',
      'frontend/packages/runtime-client/src/scenario-player-model.ts',
      'frontend/packages/runtime-client/src/scenario-runtime.ts',
      'frontend/packages/ui/src/stable-compare.ts',
      'frontend/apps/ops/src/ops-runs.tsx',
      'frontend/apps/ops/src/ops-runs-source.ts',
      'frontend/apps/ops/src/ops-scenarios.tsx',
      'frontend/apps/ops/src/ops-scenarios-runtime.ts',
      'frontend/apps/ops/src/ops-ai.tsx',
      'frontend/apps/ops/src/ops-ai-decode.ts',
      'frontend/apps/ops/src/ops-ai-model.ts',
      'frontend/apps/ops/src/ops-ai-source.ts',
      'frontend/apps/ops/src/ops-ai-runtime.ts',
      'frontend/apps/ops/src/ops-ai-header.tsx',
      'frontend/apps/ops/src/ops-ai-messages.tsx',
      'frontend/apps/ops/src/ops-ai-sidebar.tsx',
      'frontend/apps/wallet/src/wallet-scenario-preview.tsx',
    ],
    behavior: [
      'run inspection',
      'scenario execution',
      'AI sessions and embed mode',
      'React-owned filterable run authority ledger with explicit failure evidence',
      'React-owned deterministic BrowserVM scenario execution, committed-frame playback, and teardown',
      'cross-application wallet preview reconstructed from scenario identity and frame index',
      'React-owned local AI console: chat, council deliberation, agent tools, voice wake word, camera vision, and MLX model control',
    ],
    status: 'in_progress',
  },
  {
    id: 'ops-workspace',
    owner: 'ops',
    routes: ['/embed'],
    currentSources: [
      'frontend/src/lib/view/View.svelte',
      'frontend/src/routes/embed/+page.svelte',
      'frontend/packages/runtime-client/src/console-panel-view.ts',
      'frontend/packages/runtime-client/src/runtime-io-panel-view.ts',
      'frontend/packages/runtime-client/src/solvency-panel-view.ts',
      'frontend/packages/runtime-client/src/runtime-diagnostics-panel-view.ts',
      'frontend/packages/runtime-client/src/gossip-panel-view.ts',
      'frontend/packages/runtime-client/src/time-machine-transport.ts',
      'frontend/packages/runtime-client/src/jurisdiction-panel-view.ts',
      'frontend/packages/runtime-client/src/settings-panel-view.ts',
      'frontend/packages/runtime-client/src/architect-panel-view.ts',
      'frontend/packages/runtime-client/src/graph3d-entity-panel-view.ts',
      'frontend/packages/runtime-client/src/graph3d-viewport-view.ts',
      'frontend/packages/runtime-client/src/graph3d-scene-input.ts',
      'frontend/packages/runtime-client/src/entity-workspace-navigation.ts',
      'frontend/packages/runtime-client/src/entity-workspace-context.ts',
      'frontend/packages/runtime-client/src/entity-workspace-accounts.ts',
      'frontend/packages/runtime-client/src/entity-workspace-ownership.ts',
      'frontend/packages/runtime-client/src/workspace-dock-layout.ts',
      'frontend/packages/ui/src/workspace-dock.tsx',
      'frontend/packages/ui/src/entity-workspace-display.ts',
      'frontend/packages/ui/src/entity-workspace-accounts-panel.tsx',
      'frontend/packages/ui/src/entity-workspace-accounts-panel.css',
      'frontend/packages/ui/src/entity-workspace-shell.tsx',
      'frontend/packages/ui/src/entity-workspace-shell.css',
      'frontend/apps/ops/src/ops-entity-workspace.tsx',
      'frontend/apps/ops/src/ops-entity-workspace-source.ts',
      'frontend/apps/ops/src/ops-entity-workspace-runtime.ts',
      'frontend/packages/ui/src/graph3d-lifecycle.ts',
      'frontend/packages/ui/src/graph3d-renderer.ts',
      'frontend/packages/ui/src/graph3d-scene-primitives.ts',
      'frontend/packages/ui/src/graph3d-visual-effects.ts',
      'frontend/packages/ui/src/graph3d-entity-visuals.ts',
    ],
    behavior: [
      'Dockview layout',
      'Graph3D and Architect',
      'Runtime I/O, console, Solvency, Runtime Diagnostics, Gossip, and Time Machine',
      'framework-neutral panel projections shared with the canonical Svelte workspace',
      'framework-neutral Graph3D entity mini-panel projection with time-travel-aware Map/Record normalization',
      'framework-neutral Graph3D projection status, timeline, FPS, bars-mode, and VR HUD presentation state',
      'framework-neutral Graph3D runtime/jurisdiction scene inputs and recursive transaction normalization',
      'framework-neutral Entity workspace deep-link state, top-level section registry, strict identity/context, committed-board, and paged Account frame-header projections',
      'React candidate-only identity-first Entity shell with canonical hash-backed tabs, a tab-confined remote Runtime read boundary, and read-only Ownership and Accounts evidence',
      'shared Svelte-compatible layout persistence and a lifecycle-safe React Dockview adapter',
      'framework-neutral Graph3D canvas, controls, resize, debug, renderer, and XR teardown boundaries',
      'shared Three.js renderer selection plus explicit geometry, material, and texture disposal',
      'shared Graph3D grid, Jurisdiction mesh, broadcast animation, and deterministic radial layout primitives',
      'shared directional-lightning and transaction-ripple visual effects',
      'shared Graph3D entity labels, mempool indicators, and node construction',
    ],
    status: 'in_progress',
  },
] as const satisfies readonly CapabilityDefinition[];
