import type { SurfaceId } from './surfaces';

export type CapabilityStatus = 'unstarted' | 'in_progress' | 'implemented' | 'verified' | 'blocked';

export type CapabilityDefinition = Readonly<{
  id: string;
  owner: SurfaceId;
  routes: readonly `/${string}`[];
  currentSources: readonly string[];
  behavior: readonly string[];
  status: CapabilityStatus;
}>;

export const CAPABILITIES = [
  {
    id: 'site-public-information',
    owner: 'site',
    routes: ['/', '/install', '/rcpan', '/releases', '/reviews', '/unicast', '/market-cap'],
    currentSources: [
      'frontend/src/routes/+page.svelte',
      'frontend/src/routes/install/+page.svelte',
      'frontend/apps/site/src/landing-page.tsx',
      'frontend/apps/site/src/install-page.tsx',
      'frontend/apps/site/src/rcpan-page.tsx',
      'frontend/apps/site/src/unicast-page.tsx',
      'frontend/apps/site/src/releases-page.tsx',
      'frontend/apps/site/src/reviews-page.tsx',
      'frontend/apps/site/src/market-cap-page.tsx',
    ],
    behavior: ['public navigation', 'install detection', 'deterministic RCPAN dispute microscope', 'broadcast/unicast scale visualization', 'verified release ledger', 'AI review prompt slideshow', 'live market-cap data'],
    status: 'implemented',
  },
  {
    id: 'docs-reader',
    owner: 'docs',
    routes: ['/docs'],
    currentSources: [
      'frontend/src/routes/docs/+page.svelte',
      'frontend/src/lib/docs/docs-page-model.ts',
      'frontend/apps/docs/src/docs-app.tsx',
      'frontend/docs-catalog.js',
    ],
    behavior: ['catalog navigation and search', 'live/archive scope', 'safe Markdown rendering', 'deep links, anchors, and history', 'deterministic docs and llms outputs'],
    status: 'implemented',
  },
  {
    id: 'wallet-shell-and-identity',
    owner: 'wallet',
    routes: ['/app', '/address', '/testnet'],
    currentSources: [
      'frontend/packages/browser/src/wallet-boot-lifecycle.ts',
      'frontend/packages/browser/src/wallet-deploy-version.ts',
      'frontend/packages/browser/src/wallet-identity-entry.ts',
      'frontend/packages/browser/src/wallet-recovery-choice.ts',
      'frontend/packages/browser/src/wallet-recovery-rehearsal.ts',
      'frontend/packages/browser/src/wallet-runtime-bootstrap.ts',
      'frontend/packages/browser/src/wallet-runtime-consent.ts',
      'frontend/packages/browser/src/wallet-runtime-opening.ts',
      'frontend/packages/browser/src/wallet-shell-state.ts',
      'frontend/src/lib/components/Views/RuntimeCreation.svelte',
      'frontend/src/routes/app/+layout.svelte',
      'frontend/src/routes/app/+page.svelte',
      'frontend/src/routes/address/+page.svelte',
      'frontend/src/routes/testnet/+page.svelte',
      'frontend/apps/wallet/src/testnet-page.tsx',
    ],
    behavior: [
      'boot and shell',
      'generation-safe local and remote boot sequencing',
      'validated deploy-version persistence, reset, and recovery decisions',
      'canonical identity-mode selection, sensitive-field clearing, and keyboard navigation',
      'deterministic recovery candidate selection, merge ordering, and continuation',
      'verified mnemonic recovery-rehearsal transitions and reset policy',
      'ordered local-pairing, remote-import, and consent bootstrap',
      'validated remote consent and embedded cancellation ordering',
      'deterministic local unlock and Runtime creation planning',
      'framework-neutral wallet shell phase precedence',
      'identity selection',
      'onboarding and settings',
      'testnet launcher and disposable identities',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-browser-lifecycle',
    owner: 'wallet',
    routes: ['/app', '/testnet'],
    currentSources: [
      'frontend/packages/browser/src/active-tab-lock.ts',
      'frontend/packages/browser/src/browser-runtime-reset.ts',
      'frontend/packages/browser/src/hard-reset-request.ts',
      'frontend/src/lib/utils/control/resetEverything.ts',
    ],
    behavior: [
      'validated destructive reset',
      'cross-tab reset notification',
      'exclusive cross-tab Runtime ownership and quiesced takeover',
      'storage, cache, and service-worker cleanup',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-runtime-discovery',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/packages/browser/src/runtime-adapter-session.ts',
      'frontend/packages/runtime-client/src/runtime-adapter-activation.ts',
      'frontend/packages/runtime-client/src/runtime-handle.ts',
      'frontend/packages/runtime-client/src/remote-runtime-request.ts',
      'frontend/packages/runtime-client/src/runtime-query-client.ts',
      'frontend/packages/runtime-client/src/runtime-query-observer.ts',
      'frontend/packages/runtime-client/src/runtime-selection.ts',
      'frontend/packages/runtime-client/src/runtime-view-catchup.ts',
      'frontend/packages/runtime-client/src/runtime-view-loader.ts',
      'frontend/packages/runtime-client/src/runtime-view-model.ts',
      'frontend/packages/runtime-client/src/runtime-view-projections.ts',
      'frontend/packages/runtime-client/src/runtime-view-publication.ts',
      'frontend/packages/runtime-client/src/runtime-view-refresh.ts',
      'frontend/packages/runtime-client/src/runtime-view-selection.ts',
      'frontend/packages/runtime-client/src/runtime-view-state.ts',
      'frontend/packages/runtime-client/src/ws-url.ts',
      'frontend/src/lib/utils/runtime/runtimeConnection.ts',
    ],
    behavior: [
      'Runtime discovery',
      'validated hash bootstrap and query rejection',
      'tab-confined Runtime authority and rollback-safe adapter selection',
      'framework-neutral Runtime handle identity, permissions, and readiness',
      'framework-neutral adapter activation ordering and rollback',
      'framework-neutral cached Runtime projection reads and path validation',
      'framework-neutral latest-read Runtime query subscriptions and snapshots',
      'one-writer latest-intent Runtime selection',
      'framework-neutral committed-height RuntimeView catch-up',
      'framework-neutral injected RuntimeView loading and outcomes',
      'framework-neutral RuntimeView query, pagination, and height model',
      'framework-neutral selection-scoped detached RuntimeView projection reads',
      'framework-neutral latest-wins RuntimeView publication coordination',
      'framework-neutral RuntimeView refresh leases and invalidation',
      'framework-neutral RuntimeView selection snapshots and revisions',
      'framework-neutral RuntimeView snapshot and height transitions',
      'explicit remote attachment consent',
      'reconnect and failure states',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-recovery',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: ['frontend/src/lib/utils/recovery'],
    behavior: ['tower onboarding', 'recovery', 'push wake'],
    status: 'unstarted',
  },
  {
    id: 'wallet-finance',
    owner: 'wallet',
    routes: ['/app', '/address'],
    currentSources: ['frontend/src/lib/components/Entity'],
    behavior: ['assets and accounts', 'credit and collateral', 'debt, solvency, and disputes'],
    status: 'unstarted',
  },
  {
    id: 'wallet-payments-and-markets',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: ['frontend/src/lib/components/Entity/swap'],
    behavior: ['pay and receive', 'invoices and moves', 'orders, routing, and settlement'],
    status: 'unstarted',
  },
  {
    id: 'wallet-native-and-offline',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/src/lib/native',
      'frontend/capacitor.config.ts',
      'frontend/config/generated-inputs.ts',
      'frontend/apps/wallet/index.html',
      'frontend/static/site.webmanifest',
      'frontend/static/push-wake-sw.js',
      'frontend/static/route-mode.js',
    ],
    behavior: [
      'deep links',
      'PWA and offline lifecycle',
      'mobile, desktop, and extension packaging',
      'deterministic PWA and push-wake assets',
    ],
    status: 'in_progress',
  },
  {
    id: 'ops-health-and-qa',
    owner: 'ops',
    routes: ['/health', '/qa', '/qa/hlt'],
    currentSources: ['frontend/src/routes/health/+page.svelte', 'frontend/src/routes/qa/+page.svelte'],
    behavior: ['health state', 'QA evidence', 'HLT controls and results'],
    status: 'unstarted',
  },
  {
    id: 'ops-runs-scenarios-and-ai',
    owner: 'ops',
    routes: ['/runs', '/scenarios', '/ai', '/embed'],
    currentSources: ['frontend/src/routes/runs/+page.svelte', 'frontend/src/routes/scenarios/+page.svelte'],
    behavior: ['run inspection', 'scenario execution', 'AI sessions and embed mode'],
    status: 'unstarted',
  },
  {
    id: 'ops-workspace',
    owner: 'ops',
    routes: ['/embed'],
    currentSources: ['frontend/src/lib/components/Workspace'],
    behavior: ['Dockview layout', 'Graph3D and Architect', 'Runtime I/O, console, and Time Machine'],
    status: 'unstarted',
  },
] as const satisfies readonly CapabilityDefinition[];
