;; Not a bug: a WIDENING of the page's link. The page's `deliver` takes the head of the inbox (FIFO). Quint's network is a set and
;; delivers any message in flight. This adds `deliver the n-th message` for n = 1 and 2, so the receiver may take any of the first three.
;; The first page's world (the clock is off): the widening is the link's, the clock world is the default config's.
(define left-txs  (vector "a"))
(define right-txs (vector "x" "y"))
(define conflicts (vector (vector "a" "x")))
(define max-losses 1)
(define max-dups 1)
(define max-reflect 0)
(define max-clock 0)
(define (deliver-nth n)
  (rule (str "deliver " n) (w side)
    (when (> (length (inbox-of w side)) n))
    (then (let* ((q (inbox-of w side))
                 (m (list-ref q n))
                 (out (receive side (side w) m (view-at w 0))))
            (-> w (assoc-in (list side) (:replica out))
                  (assoc-in (list :inbox side) (append (take q n) (list-tail q (+ n 1))))
                  (enqueue (peer side) (filter keep-msg? (:sent out))))))))
(define (all-rules) (append (base-rules) (lag-rules) (list (deliver-nth 1) (deliver-nth 2))))
