/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface ConsoleInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "LogAddress"
      | "LogBool"
      | "LogBytes"
      | "LogBytes32"
      | "LogInt"
      | "LogString"
      | "LogUint"
  ): EventFragment;
}

export namespace LogAddressEvent {
  export type InputTuple = [arg0: string, arg1: AddressLike];
  export type OutputTuple = [arg0: string, arg1: string];
  export interface OutputObject {
    arg0: string;
    arg1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogBoolEvent {
  export type InputTuple = [arg0: string, arg1: boolean];
  export type OutputTuple = [arg0: string, arg1: boolean];
  export interface OutputObject {
    arg0: string;
    arg1: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogBytesEvent {
  export type InputTuple = [arg0: string, arg1: BytesLike];
  export type OutputTuple = [arg0: string, arg1: string];
  export interface OutputObject {
    arg0: string;
    arg1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogBytes32Event {
  export type InputTuple = [arg0: string, arg1: BytesLike];
  export type OutputTuple = [arg0: string, arg1: string];
  export interface OutputObject {
    arg0: string;
    arg1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogIntEvent {
  export type InputTuple = [arg0: string, arg1: BigNumberish];
  export type OutputTuple = [arg0: string, arg1: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogStringEvent {
  export type InputTuple = [arg0: string, arg1: string];
  export type OutputTuple = [arg0: string, arg1: string];
  export interface OutputObject {
    arg0: string;
    arg1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogUintEvent {
  export type InputTuple = [arg0: string, arg1: BigNumberish];
  export type OutputTuple = [arg0: string, arg1: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Console extends BaseContract {
  connect(runner?: ContractRunner | null): Console;
  waitForDeployment(): Promise<this>;

  interface: ConsoleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "LogAddress"
  ): TypedContractEvent<
    LogAddressEvent.InputTuple,
    LogAddressEvent.OutputTuple,
    LogAddressEvent.OutputObject
  >;
  getEvent(
    key: "LogBool"
  ): TypedContractEvent<
    LogBoolEvent.InputTuple,
    LogBoolEvent.OutputTuple,
    LogBoolEvent.OutputObject
  >;
  getEvent(
    key: "LogBytes"
  ): TypedContractEvent<
    LogBytesEvent.InputTuple,
    LogBytesEvent.OutputTuple,
    LogBytesEvent.OutputObject
  >;
  getEvent(
    key: "LogBytes32"
  ): TypedContractEvent<
    LogBytes32Event.InputTuple,
    LogBytes32Event.OutputTuple,
    LogBytes32Event.OutputObject
  >;
  getEvent(
    key: "LogInt"
  ): TypedContractEvent<
    LogIntEvent.InputTuple,
    LogIntEvent.OutputTuple,
    LogIntEvent.OutputObject
  >;
  getEvent(
    key: "LogString"
  ): TypedContractEvent<
    LogStringEvent.InputTuple,
    LogStringEvent.OutputTuple,
    LogStringEvent.OutputObject
  >;
  getEvent(
    key: "LogUint"
  ): TypedContractEvent<
    LogUintEvent.InputTuple,
    LogUintEvent.OutputTuple,
    LogUintEvent.OutputObject
  >;

  filters: {
    "LogAddress(string,address)": TypedContractEvent<
      LogAddressEvent.InputTuple,
      LogAddressEvent.OutputTuple,
      LogAddressEvent.OutputObject
    >;
    LogAddress: TypedContractEvent<
      LogAddressEvent.InputTuple,
      LogAddressEvent.OutputTuple,
      LogAddressEvent.OutputObject
    >;

    "LogBool(string,bool)": TypedContractEvent<
      LogBoolEvent.InputTuple,
      LogBoolEvent.OutputTuple,
      LogBoolEvent.OutputObject
    >;
    LogBool: TypedContractEvent<
      LogBoolEvent.InputTuple,
      LogBoolEvent.OutputTuple,
      LogBoolEvent.OutputObject
    >;

    "LogBytes(string,bytes)": TypedContractEvent<
      LogBytesEvent.InputTuple,
      LogBytesEvent.OutputTuple,
      LogBytesEvent.OutputObject
    >;
    LogBytes: TypedContractEvent<
      LogBytesEvent.InputTuple,
      LogBytesEvent.OutputTuple,
      LogBytesEvent.OutputObject
    >;

    "LogBytes32(string,bytes32)": TypedContractEvent<
      LogBytes32Event.InputTuple,
      LogBytes32Event.OutputTuple,
      LogBytes32Event.OutputObject
    >;
    LogBytes32: TypedContractEvent<
      LogBytes32Event.InputTuple,
      LogBytes32Event.OutputTuple,
      LogBytes32Event.OutputObject
    >;

    "LogInt(string,int256)": TypedContractEvent<
      LogIntEvent.InputTuple,
      LogIntEvent.OutputTuple,
      LogIntEvent.OutputObject
    >;
    LogInt: TypedContractEvent<
      LogIntEvent.InputTuple,
      LogIntEvent.OutputTuple,
      LogIntEvent.OutputObject
    >;

    "LogString(string,string)": TypedContractEvent<
      LogStringEvent.InputTuple,
      LogStringEvent.OutputTuple,
      LogStringEvent.OutputObject
    >;
    LogString: TypedContractEvent<
      LogStringEvent.InputTuple,
      LogStringEvent.OutputTuple,
      LogStringEvent.OutputObject
    >;

    "LogUint(string,uint256)": TypedContractEvent<
      LogUintEvent.InputTuple,
      LogUintEvent.OutputTuple,
      LogUintEvent.OutputObject
    >;
    LogUint: TypedContractEvent<
      LogUintEvent.InputTuple,
      LogUintEvent.OutputTuple,
      LogUintEvent.OutputObject
    >;
  };
}
