/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHashLadderRevealRegistry,
  IHashLadderRevealRegistryInterface,
} from "../../../contracts/DeltaTransformer.sol/IHashLadderRevealRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "entity",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "ladderHash",
        type: "bytes32",
      },
    ],
    name: "getHashLadderReveal",
    outputs: [
      {
        internalType: "uint16",
        name: "fillRatio",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "revealedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHashLadderRevealRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IHashLadderRevealRegistryInterface {
    return new Interface(_abi) as IHashLadderRevealRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHashLadderRevealRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHashLadderRevealRegistry;
  }
}
