import { useEffect, useRef, useState } from 'react';
import { safeStringify } from '@xln/runtime/protocol/serialization';
import { deleteAiChat, executeAiTool, loadAiModel, readAiBootstrap, readAiChat, requestCouncil, saveAiChat, streamAiChat, unloadAiModel, type AiBootstrap, type AiMessage } from '../data/ops-ai-client';

const failure = (error: unknown): string => error instanceof Error ? error.message : String(error || 'OPS_AI_FAILED');
const titleFor = (messages: readonly AiMessage[]): string => messages.find(item => item.role === 'user')?.content.slice(0, 35).trim() || 'New chat';
const chatIdFromPath = (): string | null => window.location.pathname.match(/^\/ai\/([^/]+)$/)?.[1] ?? null;

export const AiPage = () => {
  const [bootstrap, setBootstrap] = useState<AiBootstrap | null>(null); const [model, setModel] = useState(''); const [chatId, setChatId] = useState(`chat-${Date.now()}`); const [messages, setMessages] = useState<readonly AiMessage[]>([]); const [input, setInput] = useState(''); const [council, setCouncil] = useState(false); const [stream, setStream] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [toolName, setToolName] = useState(''); const [toolArgs, setToolArgs] = useState('{}'); const [toolConfirm, setToolConfirm] = useState(''); const [toolResult, setToolResult] = useState(''); const requestRef = useRef<AbortController | null>(null);
  const reload = async (signal?: AbortSignal): Promise<void> => { const next = await readAiBootstrap(signal); setBootstrap(next); setModel(current => current || next.defaultModel); setToolName(current => current || next.tools[0]?.name || ''); };
  useEffect(() => {
    const controller = new AbortController(); requestRef.current = controller;
    void reload(controller.signal).then(async () => { const id = chatIdFromPath(); if (!id) return; const chat = await readAiChat(id, controller.signal); setChatId(chat.id); setMessages(chat.messages); setCouncil(chat.councilMode); }).catch(cause => { if (!controller.signal.aborted) setError(failure(cause)); });
    return () => { controller.abort(); requestRef.current = null; };
  }, []);
  const selectChat = async (id: string): Promise<void> => { requestRef.current?.abort(); const controller = new AbortController(); requestRef.current = controller; setError(null); try { const chat = await readAiChat(id, controller.signal); setChatId(chat.id); setMessages(chat.messages); setCouncil(chat.councilMode); window.history.replaceState(null, '', `/ai/${encodeURIComponent(id)}`); } catch (cause) { if (!controller.signal.aborted) setError(failure(cause)); } };
  const newChat = (): void => { requestRef.current?.abort(); setChatId(`chat-${Date.now()}`); setMessages([]); setInput(''); setStream(''); setError(null); window.history.replaceState(null, '', '/ai'); };
  const send = async (): Promise<void> => {
    const query = input.trim(); if (!query || !bootstrap || busy) return; const user: AiMessage = Object.freeze({ role: 'user', content: query, timestamp: new Date().toISOString() }); const pending = Object.freeze([...messages, user]); setMessages(pending); setInput(''); setBusy(true); setError(null); setStream('');
    const controller = new AbortController(); requestRef.current = controller;
    try { const assistant = council ? await requestCouncil(query, bootstrap.councilModels) : Object.freeze({ role: 'assistant' as const, content: await streamAiChat(model, pending, controller.signal, setStream), model, timestamp: new Date().toISOString() }); const complete = Object.freeze([...pending, assistant]); setMessages(complete); setStream(''); await saveAiChat({ id: chatId, title: titleFor(complete), messages: complete, councilMode: council }); await reload(); }
    catch (cause) { if (!controller.signal.aborted) setError(failure(cause)); } finally { setBusy(false); }
  };
  const executeTool = async (): Promise<void> => { setError(null); setToolResult(''); if (toolConfirm !== `EXECUTE ${toolName}`) { setError('OPS_AI_TOOL_CONFIRMATION_INVALID'); return; } try { const parsed: unknown = JSON.parse(toolArgs); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('OPS_AI_TOOL_ARGS_OBJECT_REQUIRED'); const result = await executeAiTool(toolName, parsed); setToolResult(safeStringify(result, 2)); setToolConfirm(''); } catch (cause) { setError(failure(cause)); } };
  return (
    <section className="ops-page ops-ai" data-testid="ops-ai-page"><header className="ops-page-head"><div><p className="ops-eyebrow">developer capability</p><h1>AI</h1><p>Local model console. Tool execution requires an exact human confirmation.</p></div><div className="ops-ai-stats"><span>memory {bootstrap?.stats.memoryUsedPct ?? 'n/a'}%</span><span>GPU {bootstrap?.stats.gpuUtilPct ?? 'n/a'}%</span><span>MLX {bootstrap?.stats.mlxModel ?? (bootstrap?.stats.mlxLoading ? 'loading' : 'idle')}</span></div></header>{error ? <div className="ops-error" role="alert" data-testid="ai-error">{error}</div> : null}
      <div className="ops-ai-layout"><aside className="ops-panel"><header><span>saved chats</span><button type="button" onClick={newChat}>New</button></header><div className="ops-list">{bootstrap?.chats.map(chat => <article key={chat.id}><button type="button" onClick={() => void selectChat(chat.id)} className={chat.id === chatId ? 'is-active' : ''}><strong>{chat.title}</strong><small>{chat.updated}</small></button><button type="button" aria-label={`Delete ${chat.title}`} onClick={() => void deleteAiChat(chat.id).then(() => reload()).catch(cause => setError(failure(cause)))}>×</button></article>)}</div></aside>
        <main className="ops-panel ops-chat"><header><select value={model} onChange={event => setModel(event.target.value)} aria-label="AI model">{bootstrap?.models.map(item => <option key={item.id} value={item.id} disabled={!item.available}>{item.name}{item.loaded ? ' · loaded' : ''}</option>)}</select><label><input type="checkbox" checked={council} onChange={event => setCouncil(event.target.checked)}/> council</label><button type="button" disabled={!model} onClick={() => void loadAiModel(model).then(() => reload()).catch(cause => setError(failure(cause)))}>Load model</button><button type="button" onClick={() => void unloadAiModel().then(() => reload()).catch(cause => setError(failure(cause)))}>Unload MLX</button></header><div className="ops-messages">{messages.map((message, index) => <article key={`${message.timestamp ?? index}:${index}`} className={`is-${message.role}`}><header><strong>{message.role}</strong><span>{message.model ?? ''}</span></header><p>{message.content}</p></article>)}{stream ? <article className="is-assistant"><p>{stream}</p></article> : null}</div><form onSubmit={event => { event.preventDefault(); void send(); }}><textarea value={input} onChange={event => setInput(event.target.value)} placeholder="Ask the local model…"/><button type="submit" disabled={busy || !input.trim()}>{busy ? 'Running…' : 'Send'}</button>{busy ? <button type="button" onClick={() => requestRef.current?.abort()}>Stop</button> : null}</form></main>
        <aside className="ops-panel ops-tools"><header><span>explicit tools</span><strong>{bootstrap?.tools.length ?? 0}</strong></header><select value={toolName} onChange={event => { setToolName(event.target.value); setToolConfirm(''); }}><option value="">Select tool</option>{bootstrap?.tools.map(tool => <option key={tool.name}>{tool.name}</option>)}</select><p>{bootstrap?.tools.find(tool => tool.name === toolName)?.description}</p><textarea value={toolArgs} onChange={event => setToolArgs(event.target.value)} aria-label="Tool JSON arguments"/><label>Type <code>EXECUTE {toolName}</code><input value={toolConfirm} onChange={event => setToolConfirm(event.target.value)}/></label><button type="button" disabled={!toolName || toolConfirm !== `EXECUTE ${toolName}`} onClick={() => void executeTool()}>Execute tool</button>{toolResult ? <pre data-testid="ai-tool-result">{toolResult}</pre> : null}</aside></div>
    </section>
  );
};
