;; Check the ledger page.   node arrival/packages/arrival-cli/dist/cli.js run ledger.check.scm   (from spec/)
(require "lib/vocabulary.scm")
(require "lib/check.scm")
(require "money/ledger.scm")
(check ledger)
