// Type tests for scheme-zod collection functions.
//
// We prove that the schemas generated by z.list(E), z.vector(E), z.array(E)
// project to the right faces:
//
// - Scheme / interpreter face (z.input or SpecInfer scheme projection):
//   used by symbol.native contracts — raw containers (APair|ANil, AVector etc.)
//   that the interpreter actually hands to native impls.
//
// - JS / rosetta face (z.output):
//   used by symbol.rosetta impls — the decoded JS arrays of the element's JS type.
//
// This is the *type-level* counterpart to the higher-level runtime exercising
// done in attestation.test.ts (which walks real pair/vector spines produced
// through full rosetta + membrane using mostly z.schemeValue contracts).
//
// These tests use the same Face machinery (_bake.ts) that real contracts rely on.

import { describe, expectTypeOf, test } from "vitest";

import * as z from "../scheme-zod/index.js";
import type { APair } from "../../values/primitives/APair.js";
import type { ANil } from "../../values/primitives/ANil.js";
import type { ACharacter } from "../../values/primitives/ACharacter.js";
import type { AString } from "../../values/primitives/AString.js";
import type { ABool } from "../../values/primitives/ABool.js";
import type { AVector } from "../../values/primitives/AVector.js";
import type { AJSArray } from "../../membrane/AJSArray.js";
import type { AListAlike, SchemeValue } from "../../values/types.js";
import { type DecodedArgs, type SpecInfer } from "../symbols/_bake.js";

type SchemeFace<S extends z.ZodTypeAny> = z.input<S>;
type JSFace<S extends z.ZodTypeAny> = z.output<S>;

describe("scheme-zod collection faces (interpreter vs JS)", () => {
  // INVARIANT: z.list(E)'s scheme face is AListAlike (interpreter container); its JS face
  // is an array of the element's JS image.
  test("z.list(E) — homogeneous", () => {
    const charList = z.list(z.char);

    type S = SchemeFace<typeof charList>;
    expectTypeOf<S>().toExtend<AListAlike>();

    type J = JSFace<typeof charList>;
    expectTypeOf<J>().toExtend<string[]>();

    expectTypeOf<DecodedArgs<[typeof charList], "scheme">>().toExtend<[AListAlike]>();
    expectTypeOf<SpecInfer<typeof charList>>().toExtend<string[]>();
  });

  // INVARIANT: z.cons(car, cdr)'s scheme face is AListAlike; its JS face is a 2-tuple of
  // the two element JS faces.
  test("z.cons(car, cdr) — the dotted-pair form", () => {
    const consShape = z.cons(z.char, z.union([z.nil, z.boolean]));

    type S = SchemeFace<typeof consShape>;
    expectTypeOf<S>().toExtend<AListAlike>();

    type J = JSFace<typeof consShape>;
    expectTypeOf<J>().toExtend<[string, null | boolean]>();
  });

  // INVARIANT: z.vector(E)'s scheme face is AVector|AJSArray; its JS face is a plain array.
  // INVARIANT: z.array(E) is a plain-array codec with its own scheme/JS face, distinct from
  // the z.vector/z.list container union.
  test("z.vector(E) and z.array(E)", () => {
    const boolVec = z.vector(z.boolean);
    type VS = SchemeFace<typeof boolVec>;
    type VJ = JSFace<typeof boolVec>;
    expectTypeOf<VS>().toExtend<AVector | AJSArray>();
    expectTypeOf<VJ>().toEqualTypeOf<boolean[]>();

    // z.array is now zod's own plain array (NOT a scheme list/vector union): a plain array of
    // the AString codec — scheme face is AString[], JS face is string[].
    const strArr = z.array(z.string);
    type AS = SchemeFace<typeof strArr>;
    type AJ = JSFace<typeof strArr>;
    expectTypeOf<AS>().toExtend<AString[]>();
    expectTypeOf<AJ>().toExtend<string[]>();
  });

  // INVARIANT: nested collections (list-of-lists, a union including nil) compose their
  // JS faces correctly.
  test("nested and complex elements", () => {
    const listOfLists = z.list(z.list(z.char));
    type J = JSFace<typeof listOfLists>;
    expectTypeOf<J>().toExtend<string[][]>();

    // element that is itself a union including nil (common for list tails)
    const weird = z.list(z.union([z.char, z.nil, z.boolean]));
    type JW = JSFace<typeof weird>;
    expectTypeOf<JW>().toExtend<(string | null | boolean)[]>();
  });

  test("using with real contract shapes (mirrors env/r7rs usage)", () => {
    const listInVecOut = {
      input: [z.list(z.schemeValue)],
      output: [z.vector(z.schemeValue)],
    } as const;

    // Native impls receive the SCHEME face (raw containers); rosetta impls the JS face.
    type In = DecodedArgs<typeof listInVecOut.input, "scheme">;
    type Out = DecodedArgs<typeof listInVecOut.output>;

    expectTypeOf<In>().toExtend<[AListAlike]>();
    // NOT `any[]` — that's vacuous (any[] accepts almost anything, so this would pass
    // even if the decode type were wrong). z.vector(z.schemeValue)'s JS face is SchemeValue[].
    expectTypeOf<Out>().toExtend<[SchemeValue[]]>();
  });

  // INVARIANT: bare z.list() (no element) still yields AListAlike scheme face /
  // SchemeValue[] JS face.
  test("z.list() (any) is still usable as before", () => {
    const anyL = z.list();
    type S = SchemeFace<typeof anyL>;
    expectTypeOf<S>().toExtend<AListAlike>();

    type J = JSFace<typeof anyL>;
    expectTypeOf<J>().toExtend<SchemeValue[]>();
  });
});

describe("scheme-zod z.dict faces (shaped vs open)", () => {
  test("z.dict({ title }) JS face is the shaped object, not an open-record union", () => {
    const shaped = z.dict({ title: z.string });
    type J = JSFace<typeof shaped>;
    expectTypeOf<J>().toEqualTypeOf<{ title: string }>();
    expectTypeOf<DecodedArgs<[typeof shaped]>>().toEqualTypeOf<[{ title: string }]>();
  });

  test("z.dict() JS face is Record<string, SchemeValue>", () => {
    const open = z.dict();
    type J = JSFace<typeof open>;
    expectTypeOf<J>().toExtend<Record<string, SchemeValue>>();
  });
});
