/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IHashLadderRevealRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getHashLadderReveal"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getHashLadderReveal",
    values: [BytesLike, BytesLike, BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getHashLadderReveal",
    data: BytesLike
  ): Result;
}

export interface IHashLadderRevealRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IHashLadderRevealRegistry;
  waitForDeployment(): Promise<this>;

  interface: IHashLadderRevealRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getHashLadderReveal: TypedContractMethod<
    [
      ownerEntity: BytesLike,
      counterpartyEntity: BytesLike,
      ladderHash: BytesLike,
      targetRole: boolean
    ],
    [[bigint, bigint] & { fillRatio: bigint; revealedAt: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getHashLadderReveal"
  ): TypedContractMethod<
    [
      ownerEntity: BytesLike,
      counterpartyEntity: BytesLike,
      ladderHash: BytesLike,
      targetRole: boolean
    ],
    [[bigint, bigint] & { fillRatio: bigint; revealedAt: bigint }],
    "view"
  >;

  filters: {};
}
