import {
	ArrowDownLeft,
	ArrowRight,
	ArrowUpDown,
	ArrowUpRight,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	Clock,
	Copy,
	Eye,
	EyeOff,
	Home,
	Landmark,
	Link2,
	ListFilter,
	Lock,
	Moon,
	Plus,
	QrCode,
	RefreshCw,
	ScanLine,
	ShieldCheck,
	SlidersHorizontal,
	Sun,
	Trash2,
	Users,
	Wallet,
	X,
	Zap,
} from 'lucide-react';

export const icons = {
	home: Home,
	activity: Clock,
	settings: SlidersHorizontal,
	pay: ArrowUpRight,
	receive: ArrowDownLeft,
	swap: ArrowUpDown,
	chevronRight: ChevronRight,
	chevronDown: ChevronDown,
	chevronLeft: ChevronLeft,
	check: Check,
	close: X,
	shield: ShieldCheck,
	link: Link2,
	scan: ScanLine,
	plus: Plus,
	arrow: ArrowRight,
	bolt: Zap,
	filter: ListFilter,
	copy: Copy,
	lock: Lock,
	sun: Sun,
	moon: Moon,
	bank: Landmark,
	eye: Eye,
	eyeOff: EyeOff,
	qr: QrCode,
	refresh: RefreshCw,
	wallet: Wallet,
	accounts: Users,
	trash: Trash2,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, size = 17, strokeWidth = 1.75 }: { name: IconName; size?: number; strokeWidth?: number }) {
	const Component = icons[name];
	return <Component size={size} strokeWidth={strokeWidth} aria-hidden />;
}
