[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
optimizer = true
optimizer_runs = 1000
via_ir = true
solc_version = "0.8.24"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config