/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CrossSwapPull {
  export type PullStruct = {
    ownerIsLeft: boolean;
    addDeltaIndex: BigNumberish;
    amount: BigNumberish;
    subDeltaIndex: BigNumberish;
    revealedUntilBlock: BigNumberish;
    fullHash: BytesLike;
    partialRoot: BytesLike;
  };

  export type PullStructOutput = [
    ownerIsLeft: boolean,
    addDeltaIndex: bigint,
    amount: bigint,
    subDeltaIndex: bigint,
    revealedUntilBlock: bigint,
    fullHash: string,
    partialRoot: string
  ] & {
    ownerIsLeft: boolean;
    addDeltaIndex: bigint;
    amount: bigint;
    subDeltaIndex: bigint;
    revealedUntilBlock: bigint;
    fullHash: string;
    partialRoot: string;
  };

  export type BatchStruct = { pulls: CrossSwapPull.PullStruct[] };

  export type BatchStructOutput = [pulls: CrossSwapPull.PullStructOutput[]] & {
    pulls: CrossSwapPull.PullStructOutput[];
  };
}

export interface CrossSwapPullInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyBatch"
      | "applyBatchWithArgumentBlocks"
      | "encodeBatch"
      | "hashToBlock"
      | "revealSecret"
      | "supportsArgumentBlocks"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "applyBatch",
    values: [BigNumberish[], BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyBatchWithArgumentBlocks",
    values: [
      BigNumberish[],
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeBatch",
    values: [CrossSwapPull.BatchStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "hashToBlock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealSecret",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsArgumentBlocks",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "applyBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "applyBatchWithArgumentBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashToBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealSecret",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsArgumentBlocks",
    data: BytesLike
  ): Result;
}

export interface CrossSwapPull extends BaseContract {
  connect(runner?: ContractRunner | null): CrossSwapPull;
  waitForDeployment(): Promise<this>;

  interface: CrossSwapPullInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyBatch: TypedContractMethod<
    [
      deltas: BigNumberish[],
      encodedBatch: BytesLike,
      leftArguments: BytesLike,
      rightArguments: BytesLike
    ],
    [bigint[]],
    "view"
  >;

  applyBatchWithArgumentBlocks: TypedContractMethod<
    [
      deltas: BigNumberish[],
      encodedBatch: BytesLike,
      leftArguments: BytesLike,
      rightArguments: BytesLike,
      leftArgumentsBlock: BigNumberish,
      rightArgumentsBlock: BigNumberish
    ],
    [bigint[]],
    "view"
  >;

  encodeBatch: TypedContractMethod<
    [b: CrossSwapPull.BatchStruct],
    [string],
    "view"
  >;

  hashToBlock: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  revealSecret: TypedContractMethod<[arg0: BytesLike], [void], "view">;

  supportsArgumentBlocks: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyBatch"
  ): TypedContractMethod<
    [
      deltas: BigNumberish[],
      encodedBatch: BytesLike,
      leftArguments: BytesLike,
      rightArguments: BytesLike
    ],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "applyBatchWithArgumentBlocks"
  ): TypedContractMethod<
    [
      deltas: BigNumberish[],
      encodedBatch: BytesLike,
      leftArguments: BytesLike,
      rightArguments: BytesLike,
      leftArgumentsBlock: BigNumberish,
      rightArgumentsBlock: BigNumberish
    ],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "encodeBatch"
  ): TypedContractMethod<[b: CrossSwapPull.BatchStruct], [string], "view">;
  getFunction(
    nameOrSignature: "hashToBlock"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealSecret"
  ): TypedContractMethod<[arg0: BytesLike], [void], "view">;
  getFunction(
    nameOrSignature: "supportsArgumentBlocks"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
