/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { HashLadder, HashLadderInterface } from "../HashLadder.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidNibbleIndex",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidNibbleValue",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220429afb15b70c74f148551cbdf6b96abcb7d92c94f60ebf8a490536f01932470964736f6c63430008240033";

  
      type HashLadderConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: HashLadderConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class HashLadder__factory extends ContractFactory {
    
      constructor(...args: HashLadderConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<HashLadder & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): HashLadder__factory {
      return super.connect(runner) as HashLadder__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): HashLadderInterface {
      return new Interface(_abi) as HashLadderInterface;
    }
    
    override attach(address: string | Addressable): HashLadder {
      return super.attach(address) as HashLadder;
    }
  static connect(address: string, runner?: ContractRunner | null): HashLadder {
      return new Contract(address, _abi, runner) as unknown as HashLadder;
    }
  }

  
  