import { FRONTEND_ROUTES, type FrontendRoute } from '../../frontend/src/lib/contracts/frontendSurfaces';

const pageHeaders = `        default_type text/html;
        add_header Content-Security-Policy "frame-ancestors 'self'" always;`;

const assertFrontendRoot = (frontendRoot: string): void => {
  if (!/^\/[A-Za-z0-9._/-]+$/.test(frontendRoot) || frontendRoot.includes('/../')) {
    throw new Error(`FRONTEND_NGINX_ROOT_INVALID:${frontendRoot}`);
  }
};
const rootDirective = (frontendRoot: string, surface: string): string =>
  `        root ${frontendRoot}/current/${surface};`;

const pageLocation = (route: FrontendRoute, frontendRoot: string): string => {
  const root = rootDirective(frontendRoot, route.surface);
  const output = `/${route.outputEntry}`;
  if (route.pattern.includes(':entityId')) {
    return `    location ~ ^/address/[^/]+/?$ {\n${root}\n        try_files ${output} =404;\n${pageHeaders}\n    }`;
  }
  if (route.pattern.includes(':chatId?')) {
    return `    location ~ ^/ai(?:/[^/]+)?/?$ {\n${root}\n        try_files ${output} =404;\n${pageHeaders}\n    }`;
  }
  return `    location = ${route.pattern} {\n${root}\n        try_files ${output} =404;\n${pageHeaders}\n    }`;
};

const resourceLocation = (route: FrontendRoute, frontendRoot: string): string => {
  const root = rootDirective(frontendRoot, route.surface);
  if (route.pattern.endsWith('/**')) {
    const prefix = route.pattern.slice(0, -2);
    return `    location ^~ ${prefix} {\n${root}\n        try_files $uri =404;\n    }`;
  }
  return `    location = ${route.pattern} {\n${root}\n        try_files $uri =404;\n    }`;
};

const edgeLocation = (route: FrontendRoute): string => {
  if (route.pattern === '/admin') return '    location = /admin { return 308 /health; }';
  if (route.pattern === '/radapter') return '    location = /radapter { return 308 /app; }';
  return `    # ${route.id} ${route.pattern} remains runtime/edge-owned`;
};

const routeLocation = (route: FrontendRoute, frontendRoot: string): string => {
  const marker = `    # route:${route.id}`;
  if (route.surface === 'edge') return `${marker}\n${edgeLocation(route)}`;
  if (route.kind === 'resource') return `${marker}\n${resourceLocation(route, frontendRoot)}`;
  return `${marker}\n${pageLocation(route, frontendRoot)}`;
};

const identityLocations = (frontendRoot: string): string => ['site', 'docs', 'wallet', 'ops']
  .map(surface => `    location = /.well-known/xln-build/${surface}.json {
        root ${frontendRoot}/current/${surface};
        try_files /build-identity.json =404;
        default_type application/json;
        add_header Cache-Control "no-store, max-age=0" always;
    }`)
  .join('\n\n');

const sharedAssetLocations = (frontendRoot: string): string => `    location ^~ /_app/ {
        root ${frontendRoot}/current/site;
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~ ^/(?:favicon(?:-[0-9]+x[0-9]+)?\\.png|favicon\\.ico|apple-touch-icon\\.png|android-chrome-[0-9]+x[0-9]+\\.png)$ {
        root ${frontendRoot}/current/site;
        try_files $uri =404;
    }

    location ^~ /img/ { root ${frontendRoot}/current/site; try_files $uri =404; }
    location ^~ /bikes/ { root ${frontendRoot}/current/site; try_files $uri =404; }
    location ^~ /news/ { root ${frontendRoot}/current/site; try_files $uri =404; }
    location ^~ /sounds/ { root ${frontendRoot}/current/wallet; try_files $uri =404; }
    location ^~ /contracts/ { root ${frontendRoot}/current/wallet; try_files $uri =404; }
    location ~ ^/hash-wasm-[A-Za-z0-9._-]+\\.js$ { root ${frontendRoot}/current/wallet; try_files $uri =404; }`;

export const buildFrontendNginxConfig = (frontendRoot: string): string => {
  assertFrontendRoot(frontendRoot);
  const routes = FRONTEND_ROUTES.map(route => routeLocation(route, frontendRoot)).join('\n\n');
  return `# Generated by scripts/deployment/frontend-nginx-config.ts. Do not edit on-host.\n\n${routes}\n\n${identityLocations(frontendRoot)}\n\n${sharedAssetLocations(frontendRoot)}\n\n    # No universal SPA fallback: unknown paths never cross surface boundaries.\n    location / { return 404; }\n`;
};
